kafka:
  build: .
  ports:
  - 9092:9092/tcp
  labels:
    io.rancher.container.hostname_override: container_name
  links:
  - zookeeper:zookeeper
  volumes:
  - /opt/kafka/conf/server.properties:/kafka/config/server.properties
