kafka:
  ports:
  - 9092:9092/tcp
  labels:
    io.rancher.container.hostname_override: container_name
  image: kafka:0.10.0.0-alpine
  links:
  - zookeeper:zookeeper
  volumes:
  - /opt/kafka/conf/server.properties:/kafka/config/server.properties
